/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: ₦₥₵ ฿₵ (https://sketchfab.com/nmcbc)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/box-set-67917e76abf94c7b9c0de65d1052e036
Title: Box Set
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/box_set/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-0.097, -0.008, 0.138]} rotation={[-Math.PI / 2, 0.72, -Math.PI]} scale={[0.483, 0.286, 0.382]}>
          <mesh geometry={nodes['Material_004-material'].geometry} material={materials['Material.004']} />
          <mesh geometry={nodes['Material_005-material'].geometry} material={materials['Material.005']} />
        </group>
        <mesh geometry={nodes['Material_001-material'].geometry} material={materials['Material.001']} position={[-0.046, 0.006, 0.158]} rotation={[0, 0, 2.52]} scale={[0.823, 0.823, 0.325]} />
        <mesh geometry={nodes['Material_002-material'].geometry} material={materials['Material.002']} position={[-0.046, 0.006, 0.158]} rotation={[0, 0, 2.52]} scale={[0.823, 0.823, 0.325]} />
        <mesh geometry={nodes['Material_003-material'].geometry} material={materials['Material.003']} position={[-0.046, 0.006, 0.158]} rotation={[0, 0, 2.52]} scale={[0.823, 0.823, 0.325]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
